VIA_ENABLE = no
RGBLIGHT_ENABLE = yes
DEBOUNCE_TYPE = sym_eager_pk
SRC += features/layer_lock.c
CAPS_WORD_ENABLE = yes
MOUSEKEY_ENABLE = yes
# DYNAMIC_MACRO_ENABLE = yes
# DYNAMIC_MACRO_NO_NESTING = yes
